version: '4.42.1'

services:
  javajunior:
    image: ${DOCKER_REGISTRY-}javajunior
    container_name: students.app
    build:
      context: .
      dockerfile: Dockerfile
  students-db:
    image: mysql:latest
    container_name: students-db
    environment:
      - MYSQL_ROOT_PASSWORD=ADMIN
      - MYSQL_DATABASE=studentsDB
    volumes:
      - ./.containers/database:/var/lib/mysql
    ports:
      - 3306:3306